apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-api-service
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kb
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-api
  namespace: system
spec:
  ports:
  - name: api
    port: 8082
    protocol: TCP
    targetPort: api
  selector:
    control-plane: controller-manager
