{{- if and .Values.webhook.enabled .Values.certManager.enabled }}
{{- if .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "gnmic-operator.issuerName" . }}
  labels:
    {{- include "gnmic-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gnmic-operator.certificateName" . }}
  labels:
    {{- include "gnmic-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "gnmic-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "gnmic-operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certManager.issuer.kind }}
    name: {{ include "gnmic-operator.issuerName" . }}
  secretName: {{ include "gnmic-operator.certificateName" . }}
  duration: {{ .Values.certManager.duration }}
  renewBefore: {{ .Values.certManager.renewBefore }}
{{- end }}
