{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnmic-operator.webhookServiceName" . }}
  labels:
    {{- include "gnmic-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "gnmic-operator.selectorLabels" . | nindent 4 }}
{{- end }}
