# This rule is not used by the project gnmic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the operator.gnmic.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gnmic-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunneltargetpolicy-editor-role
rules:
- apiGroups:
  - operator.gnmic.dev
  resources:
  - tunneltargetpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.gnmic.dev
  resources:
  - tunneltargetpolicies/status
  verbs:
  - get
