## Append samples of your project ##
resources:
- operator_v1alpha1_cluster.yaml
- operator_v1alpha1_pipeline.yaml
- operator_v1alpha1_target.yaml
- operator_v1alpha1_targetprofile.yaml
- operator_v1alpha1_subscription.yaml
- operator_v1alpha1_output.yaml
- operator_v1alpha1_input.yaml
- operator_v1alpha1_processor.yaml
- operator_v1alpha1_tunneltargetpolicy.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
