apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetProfile
metadata:
  labels:
    app.kubernetes.io/name: targetprofile
    app.kubernetes.io/instance: targetprofile-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: targetprofile-sample
spec:
  # TODO(user): Add fields here
