apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
