apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetSource
metadata:
  labels:
    app.kubernetes.io/name: targetsource
    app.kubernetes.io/instance: targetsource-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: targetsource-sample
spec:
  # TODO(user): Add fields here
