apiVersion: operator.gnmic.dev/v1alpha1
kind: Input
metadata:
  labels:
    app.kubernetes.io/name: input
    app.kubernetes.io/instance: input-sample
    app.kubernetes.io/part-of: gnmic-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gnmic-operator
  name: input-sample
spec:
  # TODO(user): Add fields here
