apiVersion: operator.gnmic.dev/v1alpha1
kind: Target
metadata:
  labels:
    app.kubernetes.io/name: target
    app.kubernetes.io/instance: target-sample
    app.kubernetes.io/part-of: kb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kb
  name: target-sample
spec:
  # TODO(user): Add fields here
