# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.gnmic.dev_clusters.yaml
- bases/operator.gnmic.dev_pipelines.yaml
- bases/operator.gnmic.dev_targets.yaml
- bases/operator.gnmic.dev_targetprofiles.yaml
- bases/operator.gnmic.dev_targetsources.yaml
- bases/operator.gnmic.dev_subscriptions.yaml
- bases/operator.gnmic.dev_outputs.yaml
- bases/operator.gnmic.dev_inputs.yaml
- bases/operator.gnmic.dev_processors.yaml
- bases/operator.gnmic.dev_tunneltargetpolicies.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_clusters.yaml
#- path: patches/webhook_in_pipelines.yaml
#- path: patches/webhook_in_targets.yaml
#- path: patches/webhook_in_targetprofiles.yaml
#- path: patches/webhook_in_subscriptions.yaml
#- path: patches/webhook_in_outputs.yaml
#- path: patches/webhook_in_inputs.yaml
#- path: patches/webhook_in_processors.yaml
- path: patches/webhook_in_targetsources.yaml
- path: patches/webhook_in_clusters.yaml
- path: patches/webhook_in_pipelines.yaml
- path: patches/webhook_in_subscriptions.yaml
- path: patches/webhook_in_targets.yaml
- path: patches/webhook_in_outputs.yaml
- path: patches/webhook_in_inputs.yaml
- path: patches/webhook_in_processors.yaml
- path: patches/webhook_in_targetprofiles.yaml
- path: patches/webhook_in_tunneltargetpolicies.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_clusters.yaml
#- path: patches/cainjection_in_pipelines.yaml
#- path: patches/cainjection_in_targets.yaml
#- path: patches/cainjection_in_targetprofiles.yaml
#- path: patches/cainjection_in_subscriptions.yaml
#- path: patches/cainjection_in_outputs.yaml
#- path: patches/cainjection_in_inputs.yaml
#- path: patches/cainjection_in_processors.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
- kustomizeconfig.yaml
