---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.0
  name: tunneltargetpolicies.operator.gnmic.dev
spec:
  group: operator.gnmic.dev
  names:
    kind: TunnelTargetPolicy
    listKind: TunnelTargetPolicyList
    plural: tunneltargetpolicies
    singular: tunneltargetpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TunnelTargetPolicy is the Schema for the tunneltargetpolicies
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of TunnelTargetPolicy
            properties:
              match:
                description: |-
                  The match criteria for the target
                  Not required, if not set, the policy will match all targets.
                properties:
                  id:
                    description: A regex to match the target ID received in the gRPC
                      tunnel Register Target RPC.
                    type: string
                  type:
                    description: A regex to match the target type received in the
                      gRPC tunnel Register Target RPC.
                    type: string
                required:
                - id
                - type
                type: object
              profile:
                description: |-
                  The target profile to use for the matching targets
                  kubebuilder:validation:Required
                type: string
            required:
            - profile
            type: object
          status:
            description: status defines the observed state of TunnelTargetPolicy
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
